### ISSUE TITLE
add vip users

### ISSUE THREAD

**Issue by petrev1k** [olnaz/node-vkbot#2]
How to add the VIP of users?
-------------------
users.json :
{1212112,12121212,12121212}
So correctly?

**Comment by olnaz** [comment]
{
  123: [444,555,666],
  456: 'all',
  789: [777,111]
}

123 имеет vip у ботов 444, 555, 666.
456 имеет vip у всех ботов.
789 имеет vip у ботов 777, 111.

Все числа - ID аккаунтов.
