### ISSUE TITLE
После обновления - боты не работают.

### ISSUE THREAD

**Issue by petrev1k** [olnaz/node-vkbot#3]
Перекачал файлы - боты перестали отвечать, льются ошибки в логи.

**Comment by petrev1k** [comment]
Ошибка в processing.js - 155 строка, запятая думаю не стоит.
Исправил - запускаю, создается файл с токенами - но льются ошибки: http://prntscr.com/dq0qy4

**Comment by olnaz** [comment]
Эта версия ещё не тестировалась, поэтому могут быть баги. 
Закоммитил пару фиксов, должно работать, пока не проверял.

**Comment by petrev1k** [comment]
Ошибок нет, кроме server-error, но боты отвечать не хотят. http://prntscr.com/dq0qy4
Думаю поторопился обновлять файлы я... Можно как то скачать те файлы, которые были обновлены, до обновления?

**Comment by olnaz** [comment]
Сейчас боты должны отвечать.

**Comment by petrev1k** [comment]
Все норм, но http://prntscr.com/dq21eq

**Comment by olnaz** [comment]
Отвечать долго могут из-за большой задержки (config.js#messages.delay), из-за проблем с распознаванием капчи, из-за медленного интернета (если это команды /img, /unsplash и подобные).
