### ISSUE TITLE
Некоторые вопросы.

### ISSUE THREAD

**Issue by domenick92** [olnaz/node-vkbot#4]
Здравствуйте. У меня есть пару вопросов:
1. Для чего в файле конфигурации вводить эти данные:
  'vk-group': {
    confirm: '<confirm_key>', 
    secret:  '<secret_key>', 
    token:   '<access_token>'
  }
если бот вроде никак не взаимодействует с группой, либо я ошибаюсь?
2. Как банить\добавлять вип людей через команды: http://prntscr.com/dqa2i3

**Comment by olnaz** [comment]
1. Эти данные используются для работы с VK Callback API и отправки сообщений от имени сообщества. 
2. Нужно настроить Callback API для сообщества. Об этом читайте на vk.com/dev
После настройки сможете использовать команды сообщества, отправляя сообщения с аккаунта-администратора (data/admins.json).

**Comment by burov0798** [comment]
В поле token нужно указать токен администратора группы? 
Как указать адрес,куда будут отправляться данные,если бот установлен на сервере.
Спасибо,что уделяешь внимание.

**Comment by domenick92** [comment]
В поле token нужно указать токен администратора группы?
Как указать адрес,куда будут отправляться данные,если бот установлен на сервере.
Спасибо,что уделяешь внимание.
